spring:
  main:
    banner-mode: 'off'
  boot:
    admin:
      routes:
        endpoints: 'env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,hystrix.stream,turbine.stream, activiti'

server:
  port: 9090
  ssl:
    enabled: true
    key-store: classpath:client.jks
    key-store-password: 123456
    key-password: 123456
    trust-store: classpath:client.jks
    trust-store-password: 123456
    key-alias: client

eureka:
  instance:
    hostname: DESKTOP-1LP65UA
    home-page-url: https://${eureka.instance.hostname}:${server.port}
    status-page-url: https://${eureka.instance.hostname}:${server.port}
    health-check-url: https://${eureka.instance.hostname}:${server.port}
    secure-port-enabled: true
    non-secure-port-enabled: false
    non-secure-port: ${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://admin:admin@desktop-1lp65ua:8761/eureka/


management:
  endpoints:
    health:
      show-details: 'always'
    web:
      base-path: /
      exposure:
        include: '*'
  server:
    port: 9091
  endpoint:
    health:
      enabled: true
    env:
      enabled: true
    info:
      enabled: true

info:
  app:
    encoding: UTF-8
    java:
      source: 1:8
      target: 1:8
    motd: spring boot admin