spring:
  main:
    banner-mode: 'off'
  boot:
    admin:
      client:
        username: client
        password: client
        url: https://localhost:9090

server:
  port: 9192
  ssl:
    enabled: true
    key-store: classpath:client.jks
    key-store-password: 123456
    key-password: 123456
    trust-store: classpath:client.jks
    trust-store-password: 123456
    key-alias: client

eureka:
  instance:
    hostname: GF-35436
    home-page-url: https://${eureka.instance.hostname}:${server.port}
    status-page-url: https://${eureka.instance.hostname}:${server.port}/actuator/info
    health-check-url: https://${eureka.instance.hostname}:${server.port}/actuator/health
    secure-port-enabled: true
    non-secure-port-enabled: false
    non-secure-port: ${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://admin:admin@gf-35436:8761/eureka/

management:
  endpoints:
    health:
      show-details: 'always'
    web:
      base-path: /actuator
      exposure:
        include: '*'
  server:
    port: 9192
  endpoint:
    health:
      enabled: true
    env:
      enabled: true
    info:
      enabled: true

info:
  app:
    encoding: UTF-8
    java:
      source: 1:8
      target: 1:8
    motd: hello-service


logging:
  file: /var/log/sample-boot-application.log
  pattern:
    file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'