spring:
  main:
    banner-mode: 'off'
server:
  port: 8761

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
  datacenter: tehran
  environment: production
