spring:
  main:
    banner-mode: 'off'

server:
  port: 8761
  ssl:
    enabled: true
    key-store: classpath:eureka.jks
    key-store-password: 123456
    key-password: 123456
    trust-store: classpath:eureka.jks
    trust-store-password: 123456
    key-alias: eureka
    client-auth: 'want'

eureka:
  instance:
    hostname: DESKTOP-1LP65UA
    home-page-url: https://${eureka.instance.hostname}:${server.port}
    secure-port-enabled: true
    non-secure-port-enabled: false
    secure-virtual-host-name: ${spring.application.name}
    non-secure-port: ${server.port}
    secure-port: 443
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://desktop-1lp65ua:8761/eureka/
    healthcheck:
      enabled: true