spring:
  main:
    banner-mode: 'off'

server:
  port: 9090
  ssl:
    enabled: false
    key-store: classpath:client.jks
    key-store-password: 123456
    key-password: 123456
    trust-store: classpath:client.jks
    trust-store-password: 123456
    key-alias: client

eureka:
  instance:
    hostname: GF-35436
    status-page-url: https://${eureka.instance.hostname}:${server.port}/info
    home-page-url: https://${eureka.instance.hostname}:${server.port}
    health-check-url: https://${eureka.instance.hostname}:${server.port}/health
    secure-port-enabled: true
    non-secure-port-enabled: false
    non-secure-port: ${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://gf-35436:8761/eureka/
#management:
#  endpoints:
#    web:
#      base-path: /monitoring
#      exposure:
#        include: *
#    health:
#      show-details: always
#  server:
#    port: 9090
#
#info:
#  app:
#    encoding: UTF-8
#    java:
#      source: 1:8
#      target: 1:8
#    motd: hello service